# Generated by Django 6.0.7 on 2026-08-12 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('serial_ingemol', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_producto', models.CharField(blank=True, choices=[('EQUIPO', 'Equipo'), ('CONSUMIBLE', 'Consumible'), ('HERRAMIENTA', 'Herramienta'), ('MATERIALES', 'Materiales'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_sede', to='inventario.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ALMACEN', 'Almacenista'), ('USUARIO', 'Usuario normal')], default='USUARIO', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='inventario.rolusuario')),
                ('sede_por_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_sede', to='inventario.sede')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_inventario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_responsable', to='inventario.usuario'),
        ),
        migrations.CreateModel(
            name='PrestamoConsumible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('PERDIDO', 'Perdido')], default='ENTREGADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_consumibles', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles_prestados_sede', to='inventario.sede')),
                ('usuario_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles_prestados', to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('cantidad_prestada', models.IntegerField()),
                ('cantidad_devuelta', models.IntegerField(default=0)),
                ('estado_prestamo', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_sede', to='inventario.sede')),
                ('responsable_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_entregados', to='inventario.usuario')),
                ('usuario_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_solicitados', to='inventario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_usuario', to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='inventario.usuario'),
        ),
        migrations.CreateModel(
            name='InventarioSede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField(default=0)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_prestada', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_estado', to='inventario.estadoproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_sede', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_productos', to='inventario.sede')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ubicacion', to='inventario.ubicacion')),
            ],
            options={
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
