# Generated by Django 6.0.7 on 2026-08-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='serial_ingemol',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_serializado',
            field=models.BooleanField(default=False, help_text='Marcar si requiere control de serial individual (Ej: Equipos y Máquinas)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadoproducto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventariosede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prestamoconsumible',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ElementoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_interno', models.CharField(help_text='Serial o Código interno (Ej: PU-08-223)', max_length=50, unique=True)),
                ('estatus', models.CharField(choices=[('DISPONIBLE', 'Disponible en Almacén'), ('ASIGNADO', 'Asignado a Trabajador/Montaje'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DADO_DE_BAJA', 'Dado de Baja / Perdido')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_fisico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_estados', to='inventario.estadoproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_fisicos', to='inventario.producto')),
                ('sede_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_sede', to='inventario.sede')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_ubicacion', to='inventario.ubicacion')),
            ],
        ),
    ]
