# Generated by Django 6.0.7 on 2026-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_serial_ingemol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='responsable',
        ),
    ]
