# Generated by Django 6.0.7 on 2026-08-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamoconsumible',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='prestamoconsumible',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='prestamoconsumible',
            name='usuario_prestamo',
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada / Completada')], default='ACTIVA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_entregadas', to='inventario.usuario')),
                ('responsable_recibe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to='inventario.usuario')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.sede')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('cantidad_devuelta', models.IntegerField(default=0)),
                ('estado_devolucion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Devolución'), ('DEVUELTO', 'Devuelto a Almacén'), ('DADO_DE_BAJA', 'Perdido / Dañado'), ('CONSUMIDO', 'Consumido (Material/Aseo)')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.asignacion')),
                ('elemento_fisico', models.ForeignKey(blank=True, help_text='Obligatorio solo si el producto es serializado (equipos, máquinas, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='inventario.elementofisico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_asignacion', to='inventario.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='PrestamoConsumible',
        ),
    ]
